# SPDX-License-Identifier: Apache-2.0
"""tncc.utils - Utility modules for topology detection and profiling."""

from tncc.utils.benchmark_results import (
    benchmark_environment_health,
    canonical_benchmark_run,
    default_collective_bulk_sync_benchmark_path,
    default_collective_comm_only_benchmark_path,
    default_gemm_benchmark_path,
    default_p2p_benchmark_path,
    default_pattern_benchmark_path,
    describe_runtime_metadata_snapshot,
    describe_runtime_support_snapshot,
    emit_benchmark_environment_warnings,
    figures_data_dir,
    is_canonical_benchmark_output,
    project_root,
    read_json,
    runtime_metadata_snapshot,
    runtime_support_snapshot,
    write_json,
)
from tncc.utils.feature_gates import (
    FORCE_MULTIPROCESS_TRANSPORT_ENV,
    MULTIPROCESS_DEVICE_COLLECTIVES_ENV,
    forced_multiprocess_transport,
    multiprocess_device_collectives_detail,
    multiprocess_device_collectives_enabled,
    multiprocess_device_collectives_runtime_supported,
    multiprocess_device_collectives_transport_supported,
    multiprocess_device_remote_access_detail,
    multiprocess_device_remote_access_runtime_supported,
    multiprocess_device_remote_access_transport_supported,
)
from tncc.utils.profiling import TileProfiler
from tncc.utils.topology import TopologyDetector

__all__ = [
    "TopologyDetector",
    "TileProfiler",
    "project_root",
    "figures_data_dir",
    "default_collective_bulk_sync_benchmark_path",
    "default_collective_comm_only_benchmark_path",
    "default_gemm_benchmark_path",
    "default_p2p_benchmark_path",
    "default_pattern_benchmark_path",
    "is_canonical_benchmark_output",
    "benchmark_environment_health",
    "canonical_benchmark_run",
    "emit_benchmark_environment_warnings",
    "runtime_metadata_snapshot",
    "runtime_support_snapshot",
    "describe_runtime_metadata_snapshot",
    "describe_runtime_support_snapshot",
    "FORCE_MULTIPROCESS_TRANSPORT_ENV",
    "MULTIPROCESS_DEVICE_COLLECTIVES_ENV",
    "forced_multiprocess_transport",
    "multiprocess_device_collectives_enabled",
    "multiprocess_device_collectives_detail",
    "multiprocess_device_collectives_runtime_supported",
    "multiprocess_device_collectives_transport_supported",
    "multiprocess_device_remote_access_detail",
    "multiprocess_device_remote_access_runtime_supported",
    "multiprocess_device_remote_access_transport_supported",
    "write_json",
    "read_json",
]
